apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: blog 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 3
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog-nginx
        image: pcwizz/blog:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - pcwizz.net
    secretName: blog-tls
  rules:
  - host: pcwizz.net
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-tls
spec:
  secretName: blog-tls
  duration: 2160h
  renewBefore: 360h
  usages:
    - server auth
  dnsNames:
  - pcwizz.net
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
