# The URL the site will be built for
base_url = "https://pcwizz.net"
title = "Pcwizz's blog"
description = "Nerd by the name of Pcwizz writes about DevOps, politics, and Free Software."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme= "after-dark"

taxonomies = [
	{name = "tags", rss = true},
]

[extra]
author = "Pcwizz"
after_dark_title = "Pcwizz's blog"
after_dark_menu = [
	{url = "/", name = "Home"},
	{url = "/tags", name = "Tags"},
	{url = "https://github.com/pcwizz", name = "Github"},
	{url = "https://twitter.com/pcwizz", name = "Twitter"},
]
